export const leagues = [
  {
    id: "ucl",
    name: "UEFA Champions League",
    icon: "/icons/ucl.svg",
    background:
      "/placeholder.svg?height=200&width=400&text=UEFA+Champions+League",
    region: "Europe",
    teams: 32,
    matches: 125,
    currentChampion: "Manchester City",
    championLogo: "/icons/mancity.svg",
    nextMatchDate: "2023-11-22",
  },
  {
    id: "premier",
    name: "Premier League",
    icon: "/icons/premier.svg",
    background: "/placeholder.svg?height=200&width=400&text=Premier+League",
    region: "England",
    teams: 20,
    matches: 380,
    currentChampion: "Manchester City",
    championLogo: "/icons/mancity.svg",
    nextMatchDate: "2023-11-20",
  },
  {
    id: "laliga",
    name: "La Liga",
    icon: "/icons/laliga.svg",
    background: "/placeholder.svg?height=200&width=400&text=La+Liga",
    region: "Spain",
    teams: 20,
    matches: 380,
    currentChampion: "Barcelona",
    championLogo: "/icons/barcelona.svg",
    nextMatchDate: "2023-11-18",
  },
  {
    id: "bundesliga",
    name: "Bundesliga",
    icon: "/icons/bundesliga.svg",
    background: "/placeholder.svg?height=200&width=400&text=Bundesliga",
    region: "Germany",
    teams: 18,
    matches: 306,
    currentChampion: "Bayern Munich",
    championLogo: "/icons/bayern.svg",
    nextMatchDate: "2023-11-19",
  },
  {
    id: "seriea",
    name: "Serie A",
    icon: "/icons/seriea.svg",
    background: "/placeholder.svg?height=200&width=400&text=Serie+A",
    region: "Italy",
    teams: 20,
    matches: 380,
    currentChampion: "Napoli",
    championLogo: "/icons/napoli.svg",
    nextMatchDate: "2023-11-19",
  },
  {
    id: "ligue1",
    name: "Ligue 1",
    icon: "/icons/ligue1.svg",
    background: "/placeholder.svg?height=200&width=400&text=Ligue+1",
    region: "France",
    teams: 18,
    matches: 306,
    currentChampion: "PSG",
    championLogo: "/icons/psg.svg",
    nextMatchDate: "2023-11-18",
  },
  {
    id: "uel",
    name: "UEFA Europa League",
    icon: "/icons/uel.svg",
    background: "/placeholder.svg?height=200&width=400&text=UEFA+Europa+League",
    region: "Europe",
    teams: 32,
    matches: 141,
    currentChampion: "Sevilla",
    championLogo: "/icons/sevilla.svg",
    nextMatchDate: "2023-11-23",
  },
  {
    id: "eredivisie",
    name: "Eredivisie",
    icon: "/icons/eredivisie.svg",
    background: "/placeholder.svg?height=200&width=400&text=Eredivisie",
    region: "Netherlands",
    teams: 18,
    matches: 306,
    currentChampion: "Feyenoord",
    championLogo: "/icons/feyenoord.svg",
    nextMatchDate: "2023-11-21",
  },
  {
    id: "primeiraliga",
    name: "Primeira Liga",
    icon: "/icons/primeiraliga.svg",
    background: "/placeholder.svg?height=200&width=400&text=Primeira+Liga",
    region: "Portugal",
    teams: 18,
    matches: 306,
    currentChampion: "Benfica",
    championLogo: "/icons/benfica.svg",
    nextMatchDate: "2023-11-20",
  },
];
