export const liveMatches = [
  {
    id: 1,
    phase: "Group Stage",
    group: "Group A",
    homeTeam: {
      name: "Brazil",
      code: "BRA",
      flag: "/flags/brazil.svg",
      score: 2,
      fifaRanking: 1,
    },
    awayTeam: {
      name: "Argentina",
      code: "ARG",
      flag: "/flags/argentina.svg",
      score: 1,
      fifaRanking: 2,
    },
    minute: 78,
    venue: "MetLife Stadium",
    city: "New York, USA",
    attendance: "82,500",
    temperature: "24°C",
    viewers: "2.8M",
    stats: {
      possession: [52, 48],
      shots: [15, 12],
      corners: [7, 4],
      fouls: [8, 11],
      yellowCards: [2, 3],
      redCards: [0, 0],
    },
  },
  {
    id: 2,
    phase: "Quarter Final",
    group: null,
    homeTeam: {
      name: "France",
      code: "FRA",
      flag: "/flags/france.svg",
      score: 3,
      fifaRanking: 3,
    },
    awayTeam: {
      name: "Germany",
      code: "GER",
      flag: "/flags/germany.svg",
      score: 2,
      fifaRanking: 4,
    },
    minute: 65,
    venue: "SoFi Stadium",
    city: "Los Angeles, USA",
    attendance: "70,240",
    temperature: "28°C",
    viewers: "3.2M",
    stats: {
      possession: [45, 55],
      shots: [18, 16],
      corners: [9, 6],
      fouls: [12, 9],
      yellowCards: [3, 2],
      redCards: [0, 1],
    },
  },
  {
    id: 3,
    phase: "Group Stage",
    group: "Group B",
    homeTeam: {
      name: "Spain",
      code: "ESP",
      flag: "/flags/spain.svg",
      score: 1,
      fifaRanking: 5,
    },
    awayTeam: {
      name: "Netherlands",
      code: "NED",
      flag: "/flags/netherlands.svg",
      score: 1,
      fifaRanking: 6,
    },
    minute: 34,
    venue: "Estadio Azteca",
    city: "Mexico City, Mexico",
    attendance: "87,523",
    temperature: "22°C",
    viewers: "2.1M",
    stats: {
      possession: [65, 35],
      shots: [12, 8],
      corners: [5, 2],
      fouls: [6, 14],
      yellowCards: [1, 4],
      redCards: [0, 0],
    },
  },
  {
    id: 4,
    phase: "Semi Final",
    group: null,
    homeTeam: {
      name: "England",
      code: "ENG",
      flag: "/flags/england.svg",
      score: 2,
      fifaRanking: 7,
    },
    awayTeam: {
      name: "Portugal",
      code: "POR",
      flag: "/flags/portugal.svg",
      score: 0,
      fifaRanking: 8,
    },
    minute: 82,
    venue: "AT&T Stadium",
    city: "Dallas, USA",
    attendance: "80,000",
    temperature: "26°C",
    viewers: "4.1M",
    stats: {
      possession: [48, 52],
      shots: [14, 10],
      corners: [6, 8],
      fouls: [10, 7],
      yellowCards: [2, 1],
      redCards: [0, 0],
    },
  },
  {
    id: 5,
    phase: "Group Stage",
    group: "Group C",
    homeTeam: {
      name: "Italy",
      code: "ITA",
      flag: "/flags/italy.svg",
      score: 0,
      fifaRanking: 9,
    },
    awayTeam: {
      name: "Belgium",
      code: "BEL",
      flag: "/flags/belgium.svg",
      score: 2,
      fifaRanking: 10,
    },
    minute: 55,
    venue: "BMO Field",
    city: "Toronto, Canada",
    attendance: "45,500",
    temperature: "18°C",
    viewers: "1.8M",
    stats: {
      possession: [42, 58],
      shots: [9, 13],
      corners: [3, 7],
      fouls: [15, 8],
      yellowCards: [4, 2],
      redCards: [1, 0],
    },
  },
  {
    id: 6,
    phase: "Group Stage",
    group: "Group D",
    homeTeam: {
      name: "Croatia",
      code: "CRO",
      flag: "/flags/croatia.svg",
      score: 1,
      fifaRanking: 11,
    },
    awayTeam: {
      name: "Morocco",
      code: "MAR",
      flag: "/flags/morocco.svg",
      score: 3,
      fifaRanking: 12,
    },
    minute: 70,
    venue: "BC Place",
    city: "Vancouver, Canada",
    attendance: "54,500",
    temperature: "16°C",
    viewers: "1.5M",
    stats: {
      possession: [55, 45],
      shots: [11, 16],
      corners: [4, 9],
      fouls: [9, 12],
      yellowCards: [2, 3],
      redCards: [0, 0],
    },
  },
];
