export const plans = {
  free: {
    name: "Free",
    price: 0,
    billingCycle: "monthly",
    features: [
      "SD quality streaming",
      "5 matches per month",
      "Basic match statistics",
      "Ad-supported experience",
      "Mobile and tablet access",
    ],
  },
  basic: {
    name: "Basic",
    price: 9.99,
    billingCycle: "monthly",
    features: [
      "SD quality streaming",
      "Unlimited matches",
      "Basic match statistics",
      "Ad-supported experience",
      "Mobile and tablet access",
      "HD streaming",
      "Full match replays",
    ],
  },
  premium: {
    name: "Premium",
    price: 19.99,
    billingCycle: "monthly",
    features: [
      "SD quality streaming",
      "Unlimited matches",
      "Advanced match statistics",
      "Ad-free experience",
      "Mobile and tablet access",
      "HD & 4K streaming",
      "No ads",
      "Multi-device streaming",
      "Full match replays",
    ],
  },
  ultimate: {
    name: "Ultimate",
    price: 29.99,
    billingCycle: "monthly",
    features: [
      "SD quality streaming",
      "Unlimited matches",
      "Advanced match statistics",
      "Ad-free experience",
      "Mobile and tablet access",
      "HD & 4K streaming",
      "No ads",
      "Multi-device streaming",
      "Full match replays",
      "Exclusive content",
    ],
  },
};
