export const worldCupTeams = [
  {
    id: "spain",
    name: "Spain",
    flag: "/flags/spain.svg",
    region: "Europe",
    group: "H",
    fifaRanking: 1,
    coach: "Luis de la Fuente",
    keyPlayers: ["Rodri", "Pedri", "Lamine Yamal"],
    worldCupHistory: "1-time winner",
    qualification: "UEFA",
    teamId: "43969",
    appearances: 16,
    hostTeam: false,
    primaryColor: "#FF0000",
    secondaryColor: "#FFC100",
  },
  {
    id: "argentina",
    name: "Argentina",
    flag: "/flags/argentina.svg",
    region: "South America",
    group: "J",
    fifaRanking: 2,
    coach: "Lionel Scaloni",
    keyPlayers: ["Lionel Messi", "Lautaro Martinez", "Emiliano Martinez"],
    worldCupHistory: "3-time winners",
    qualification: "CONMEBOL",
    teamId: "43922",
    appearances: 18,
    hostTeam: false,
    primaryColor: "#9CC9F2",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "france",
    name: "France",
    flag: "/flags/france.svg",
    region: "Europe",
    group: "I",
    fifaRanking: 3,
    coach: "Didier Deschamps",
    keyPlayers: ["Kylian Mbappe", "Antoine Griezmann", "Eduardo Camavinga"],
    worldCupHistory: "2-time winners",
    qualification: "UEFA",
    teamId: "43946",
    appearances: 16,
    hostTeam: false,
    primaryColor: "#00418F",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "england",
    name: "England",
    flag: "/flags/england.svg",
    region: "Europe",
    group: "L",
    fifaRanking: 4,
    coach: "Gareth Southgate",
    keyPlayers: ["Harry Kane", "Jude Bellingham", "Phil Foden"],
    worldCupHistory: "1-time winner",
    qualification: "UEFA",
    teamId: "43942",
    appearances: 16,
    hostTeam: false,
    primaryColor: "#FFFFFF",
    secondaryColor: "#CE1124",
  },
  {
    id: "brazil",
    name: "Brazil",
    flag: "/flags/brazil.svg",
    region: "South America",
    group: "C",
    fifaRanking: 5,
    coach: "Dorival Júnior",
    keyPlayers: ["Vinicius Jr.", "Rodrygo", "Alisson Becker"],
    worldCupHistory: "5-time winners",
    qualification: "CONMEBOL",
    teamId: "43924",
    appearances: 22,
    hostTeam: false,
    primaryColor: "#FFCF25",
    secondaryColor: "#004DE1",
  },
  {
    id: "portugal",
    name: "Portugal",
    flag: "/flags/portugal.svg",
    region: "Europe",
    group: "K",
    fifaRanking: 6,
    coach: "Roberto Martinez",
    keyPlayers: ["Cristiano Ronaldo", "Bruno Fernandes", "Bernardo Silva"],
    worldCupHistory: "Best: 3rd place",
    qualification: "UEFA",
    teamId: "43963",
    appearances: 8,
    hostTeam: false,
    primaryColor: "#FF0000",
    secondaryColor: "#1B7F51",
  },
  {
    id: "netherlands",
    name: "Netherlands",
    flag: "/flags/netherlands.svg",
    region: "Europe",
    group: "F",
    fifaRanking: 7,
    coach: "Ronald Koeman",
    keyPlayers: ["Virgil van Dijk", "Frenkie de Jong", "Memphis Depay"],
    worldCupHistory: "3-time runner-up",
    qualification: "UEFA",
    teamId: "43960",
    appearances: 10,
    hostTeam: false,
    primaryColor: "#FF7A00",
    secondaryColor: "#21468B",
  },
  {
    id: "morocco",
    name: "Morocco",
    flag: "/flags/morocco.svg",
    region: "Africa",
    group: "C",
    fifaRanking: 8,
    coach: "Walid Regragui",
    keyPlayers: ["Hakim Ziyech", "Achraf Hakimi", "Yassine Bounou"],
    worldCupHistory: "Best: 4th place (2022)",
    qualification: "CAF",
    teamId: "43872",
    appearances: 6,
    hostTeam: false,
    primaryColor: "#E40000",
    secondaryColor: "#02853D",
  },
  {
    id: "belgium",
    name: "Belgium",
    flag: "/flags/belgium.svg",
    region: "Europe",
    group: "G",
    fifaRanking: 9,
    coach: "Domenico Tedesco",
    keyPlayers: ["Kevin De Bruyne", "Romelu Lukaku", "Thibaut Courtois"],
    worldCupHistory: "Best: 3rd place (2018)",
    qualification: "UEFA",
    teamId: "43935",
    appearances: 13,
    hostTeam: false,
    primaryColor: "#880029",
    secondaryColor: "#DFA000",
  },
  {
    id: "germany",
    name: "Germany",
    flag: "/flags/germany.svg",
    region: "Europe",
    group: "E",
    fifaRanking: 10,
    coach: "Julian Nagelsmann",
    keyPlayers: ["Joshua Kimmich", "Jamal Musiala", "Ilkay Gündogan"],
    worldCupHistory: "4-time winners",
    qualification: "UEFA",
    teamId: "43948",
    appearances: 10,
    hostTeam: false,
    primaryColor: "#1F1F1F",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "croatia",
    name: "Croatia",
    flag: "/flags/croatia.svg",
    region: "Europe",
    group: "L",
    fifaRanking: 11,
    coach: "Zlatko Dalić",
    keyPlayers: ["Luka Modrić", "Mateo Kovačić", "Marcelo Brozović"],
    worldCupHistory: "Best: 2nd place (2018)",
    qualification: "UEFA",
    teamId: "43938",
    appearances: 6,
    hostTeam: false,
    primaryColor: "#F30A0A",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "senegal",
    name: "Senegal",
    flag: "/flags/senegal.svg",
    region: "Africa",
    group: "I",
    fifaRanking: 12,
    coach: "Aliou Cissé",
    keyPlayers: ["Sadio Mané", "Kalidou Koulibaly", "Édouard Mendy"],
    worldCupHistory: "Best: Quarter-finals (2022)",
    qualification: "CAF",
    teamId: "43879",
    appearances: 3,
    hostTeam: false,
    primaryColor: "#FFDA17",
    secondaryColor: "#F8E825",
  },
  {
    id: "usa",
    name: "United States",
    flag: "/flags/usa.svg",
    region: "North America",
    group: "D",
    fifaRanking: 15,
    coach: "Gregg Berhalter",
    keyPlayers: ["Christian Pulisic", "Weston McKennie", "Tyler Adams"],
    worldCupHistory: "Best: 3rd place (1930)",
    qualification: "Host Nation",
    teamId: "43921",
    appearances: 11,
    hostTeam: true,
    primaryColor: "#0326DE",
    secondaryColor: "#DE121D",
  },
  {
    id: "mexico",
    name: "Mexico",
    flag: "/flags/mexico.svg",
    region: "North America",
    group: "A",
    fifaRanking: 16,
    coach: "Jaime Lozano",
    keyPlayers: ["Hirving Lozano", "Guillermo Ochoa", "Raul Jimenez"],
    worldCupHistory: "Best: Quarter-finals",
    qualification: "Host Nation",
    teamId: "43911",
    appearances: 17,
    hostTeam: true,
    primaryColor: "#27A550",
    secondaryColor: "#EA0000",
  },
  {
    id: "uruguay",
    name: "Uruguay",
    flag: "/flags/uruguay.svg",
    region: "South America",
    group: "H",
    fifaRanking: 17,
    coach: "Marcelo Bielsa",
    keyPlayers: ["Federico Valverde", "Darwin Núñez", "Ronald Araújo"],
    worldCupHistory: "2-time winners",
    qualification: "CONMEBOL",
    teamId: "43930",
    appearances: 14,
    hostTeam: false,
    primaryColor: "#7EC1FF",
    secondaryColor: "#FFC100",
  },
  {
    id: "switzerland",
    name: "Switzerland",
    flag: "/flags/switzerland.svg",
    region: "Europe",
    group: "B",
    fifaRanking: 18,
    coach: "Murat Yakin",
    keyPlayers: ["Granit Xhaka", "Manuel Akanji", "Yann Sommer"],
    worldCupHistory: "Best: Quarter-finals (1934, 1938, 1954)",
    qualification: "UEFA",
    teamId: "43971",
    appearances: 12,
    hostTeam: false,
    primaryColor: "#E20000",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "japan",
    name: "Japan",
    flag: "/flags/japan.svg",
    region: "Asia",
    group: "F",
    fifaRanking: 19,
    coach: "Hajime Moriyasu",
    keyPlayers: ["Kaoru Mitoma", "Takehiro Tomiyasu", "Daichi Kamada"],
    worldCupHistory: "Best: Round of 16",
    qualification: "AFC",
    teamId: "43819",
    appearances: 7,
    hostTeam: false,
    primaryColor: "#2830E7",
    secondaryColor: "#07063C",
  },
  {
    id: "iran",
    name: "IR Iran",
    flag: "/flags/iran.svg",
    region: "Asia",
    group: "G",
    fifaRanking: 20,
    coach: "Amir Ghalenoei",
    keyPlayers: ["Mehdi Taremi", "Alireza Jahanbakhsh", "Sardar Azmoun"],
    worldCupHistory: "Best: Group Stage",
    qualification: "AFC",
    teamId: "43817",
    appearances: 6,
    hostTeam: false,
    primaryColor: "#DF1818",
    secondaryColor: "#239F40",
  },
  {
    id: "south-korea",
    name: "Korea Republic",
    flag: "/flags/south-korea.svg",
    region: "Asia",
    group: "A",
    fifaRanking: 22,
    coach: "Jürgen Klinsmann",
    keyPlayers: ["Son Heung-min", "Kim Min-jae", "Lee Kang-in"],
    worldCupHistory: "Best: 4th place (2002)",
    qualification: "AFC",
    teamId: "43822",
    appearances: 10,
    hostTeam: false,
    primaryColor: "#FF253A",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "ecuador",
    name: "Ecuador",
    flag: "/flags/ecuador.svg",
    region: "South America",
    group: "E",
    fifaRanking: 23,
    coach: "Félix Sánchez",
    keyPlayers: ["Moises Caicedo", "Pervis Estupiñán", "Enner Valencia"],
    worldCupHistory: "Best: Round of 16 (2006)",
    qualification: "CONMEBOL",
    teamId: "43927",
    appearances: 4,
    hostTeam: false,
    primaryColor: "#FFD600",
    secondaryColor: "#0032E3",
  },
  {
    id: "austria",
    name: "Austria",
    flag: "/flags/austria.svg",
    region: "Europe",
    group: "J",
    fifaRanking: 24,
    coach: "Ralf Rangnick",
    keyPlayers: ["David Alaba", "Marko Arnautović", "Marcel Sabitzer"],
    worldCupHistory: "Best: 3rd place (1954)",
    qualification: "UEFA",
    teamId: "43934",
    appearances: 7,
    hostTeam: false,
    primaryColor: "#ED3D32",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "australia",
    name: "Australia",
    flag: "/flags/australia.svg",
    region: "Asia",
    group: "D",
    fifaRanking: 27,
    coach: "Graham Arnold",
    keyPlayers: ["Mathew Ryan", "Harry Souttar", "Ajdin Hrustic"],
    worldCupHistory: "Best: Round of 16 (2022)",
    qualification: "AFC",
    teamId: "43976",
    appearances: 6,
    hostTeam: false,
    primaryColor: "#FFC100",
    secondaryColor: "#00784D",
  },
  {
    id: "algeria",
    name: "Algeria",
    flag: "/flags/algeria.svg",
    region: "Africa",
    group: "J",
    fifaRanking: 28,
    coach: "Djamel Belmadi",
    keyPlayers: ["Riyad Mahrez", "Ismaël Bennacer", "Youcef Belaïli"],
    worldCupHistory: "Best: Round of 16 (2014)",
    qualification: "CAF",
    teamId: "43843",
    appearances: 4,
    hostTeam: false,
    primaryColor: "#00A067",
    secondaryColor: "#E40000",
  },
  {
    id: "canada",
    name: "Canada",
    flag: "/flags/canada.svg",
    region: "North America",
    group: "B",
    fifaRanking: 29,
    coach: "Mauro Biello",
    keyPlayers: ["Alphonso Davies", "Jonathan David", "Tajon Buchanan"],
    worldCupHistory: "Best: Group Stage",
    qualification: "Host Nation",
    teamId: "43899",
    appearances: 2,
    hostTeam: true,
    primaryColor: "#D52B1E",
    secondaryColor: "#FFFFFF",
  },
  // Adding more teams from the FIFA data
  {
    id: "egypt",
    name: "Egypt",
    flag: "/flags/egypt.svg",
    region: "Africa",
    group: "G",
    fifaRanking: 31,
    coach: "Rui Vitória",
    keyPlayers: ["Mohamed Salah", "Mohamed Elneny", "Trezequet"],
    worldCupHistory: "Best: Group Stage",
    qualification: "CAF",
    teamId: "43855",
    appearances: 3,
    hostTeam: false,
    primaryColor: "#F1051F",
    secondaryColor: "#242424",
  },
  {
    id: "norway",
    name: "Norway",
    flag: "/flags/norway.svg",
    region: "Europe",
    group: "I",
    fifaRanking: 32,
    coach: "Ståle Solbakken",
    keyPlayers: ["Erling Haaland", "Martin Ødegaard", "Sander Berge"],
    worldCupHistory: "Best: Round of 16 (1998)",
    qualification: "UEFA",
    teamId: "43961",
    appearances: 3,
    hostTeam: false,
    primaryColor: "#C70000",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "panama",
    name: "Panama",
    flag: "/flags/panama.svg",
    region: "North America",
    group: "L",
    fifaRanking: 33,
    coach: "Thomas Christiansen",
    keyPlayers: ["Aníbal Godoy", "Alberto Quintero", "José Rodríguez"],
    worldCupHistory: "Best: Group Stage (2018)",
    qualification: "CONCACAF",
    teamId: "43914",
    appearances: 1,
    hostTeam: false,
    primaryColor: "#E41027",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "colombia",
    name: "Colombia",
    flag: "/flags/colombia.svg",
    region: "South America",
    group: "K",
    fifaRanking: 14,
    coach: "Néstor Lorenzo",
    keyPlayers: ["Luis Díaz", "James Rodríguez", "David Ospina"],
    worldCupHistory: "Best: Quarter-finals (2014)",
    qualification: "CONMEBOL",
    teamId: "43926",
    appearances: 6,
    hostTeam: false,
    primaryColor: "#FFD600",
    secondaryColor: "#00148E",
  },
  {
    id: "ghana",
    name: "Ghana",
    flag: "/flags/ghana.svg",
    region: "Africa",
    group: "L",
    fifaRanking: 72,
    coach: "Chris Hughton",
    keyPlayers: ["Thomas Partey", "Mohammed Kudus", "Jordan Ayew"],
    worldCupHistory: "Best: Quarter-finals (2010)",
    qualification: "CAF",
    teamId: "43860",
    appearances: 4,
    hostTeam: false,
    primaryColor: "#FFC100",
    secondaryColor: "#CE1126",
  },
  {
    id: "qatar",
    name: "Qatar",
    flag: "/flags/qatar.svg",
    region: "Asia",
    group: "B",
    fifaRanking: 56,
    coach: "Carlos Queiroz",
    keyPlayers: ["Almoez Ali", "Akram Afif", "Hassan Al-Haydos"],
    worldCupHistory: "Best: Group Stage (2022)",
    qualification: "AFC",
    teamId: "43834",
    appearances: 1,
    hostTeam: false,
    primaryColor: "#8D1B3D",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "south-africa",
    name: "South Africa",
    flag: "/flags/south-africa.svg",
    region: "Africa",
    group: "A",
    fifaRanking: 60,
    coach: "Hugo Broos",
    keyPlayers: ["Percy Tau", "Themba Zwane", "Ronwen Williams"],
    worldCupHistory: "Best: Group Stage",
    qualification: "CAF",
    teamId: "43883",
    appearances: 3,
    hostTeam: false,
    primaryColor: "#FFD600",
    secondaryColor: "#27A550",
  },
  {
    id: "saudi-arabia",
    name: "Saudi Arabia",
    flag: "/flags/saudi-arabia.svg",
    region: "Asia",
    group: "H",
    fifaRanking: 61,
    coach: "Roberto Mancini",
    keyPlayers: ["Salem Al-Dawsari", "Firas Al-Buraikan", "Mohammed Al-Owais"],
    worldCupHistory: "Best: Round of 16 (1994)",
    qualification: "AFC",
    teamId: "43835",
    appearances: 6,
    hostTeam: false,
    primaryColor: "#27A550",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "jordan",
    name: "Jordan",
    flag: "/flags/jordan.svg",
    region: "Asia",
    group: "J",
    fifaRanking: 64,
    coach: "Hussein Ammouta",
    keyPlayers: ["Mousa Al-Taamari", "Yazan Al-Naimat", "Baha' Faisal"],
    worldCupHistory: "First appearance",
    qualification: "AFC",
    teamId: "43820",
    appearances: 0,
    hostTeam: false,
    primaryColor: "#FF1A1A",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "cabo-verde",
    name: "Cabo Verde",
    flag: "/flags/cabo-verde.svg",
    region: "Africa",
    group: "H",
    fifaRanking: 67,
    coach: "Bubista",
    keyPlayers: ["Ryan Mendes", "Jovane Cabral", "Vozinha"],
    worldCupHistory: "First appearance",
    qualification: "CAF",
    teamId: "43850",
    appearances: 0,
    hostTeam: false,
    primaryColor: "#222E77",
    secondaryColor: "#EC301A",
  },
  {
    id: "tunisia",
    name: "Tunisia",
    flag: "/flags/tunisia.svg",
    region: "Africa",
    group: "F",
    fifaRanking: 47,
    coach: "Jalel Kadri",
    keyPlayers: ["Wahbi Khazri", "Youssef Msakni", "Aïssa Laïdouni"],
    worldCupHistory: "Best: Group Stage",
    qualification: "CAF",
    teamId: "43888",
    appearances: 6,
    hostTeam: false,
    primaryColor: "#E91426",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "scotland",
    name: "Scotland",
    flag: "/flags/scotland.svg",
    region: "Europe",
    group: "C",
    fifaRanking: 38,
    coach: "Steve Clarke",
    keyPlayers: ["Andy Robertson", "John McGinn", "Scott McTominay"],
    worldCupHistory: "Best: Group Stage",
    qualification: "UEFA",
    teamId: "43967",
    appearances: 7,
    hostTeam: false,
    primaryColor: "#1E1C71",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "paraguay",
    name: "Paraguay",
    flag: "/flags/paraguay.svg",
    region: "South America",
    group: "D",
    fifaRanking: 40,
    coach: "Guillermo Barros Schelotto",
    keyPlayers: ["Miguel Almirón", "Antonio Sanabria", "Junior Alonso"],
    worldCupHistory: "Best: Quarter-finals (2010)",
    qualification: "CONMEBOL",
    teamId: "43928",
    appearances: 8,
    hostTeam: false,
    primaryColor: "#DE0000",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "ivory-coast",
    name: "Côte d'Ivoire",
    flag: "/flags/ivory-coast.svg",
    region: "Africa",
    group: "E",
    fifaRanking: 37,
    coach: "Emerse Faé",
    keyPlayers: ["Sébastien Haller", "Franck Kessié", "Simon Adingra"],
    worldCupHistory: "Best: Group Stage",
    qualification: "CAF",
    teamId: "43854",
    appearances: 3,
    hostTeam: false,
    primaryColor: "#FF8A00",
    secondaryColor: "#137A36",
  },
  {
    id: "haiti",
    name: "Haiti",
    flag: "/flags/haiti.svg",
    region: "North America",
    group: "C",
    fifaRanking: 83,
    coach: "Gabriel Calderón",
    keyPlayers: ["Duckens Nazon", "Carnejy Antoine", "Alex Junior Christian"],
    worldCupHistory: "Best: Group Stage (1974)",
    qualification: "CONCACAF",
    teamId: "43908",
    appearances: 1,
    hostTeam: false,
    primaryColor: "#0013BA",
    secondaryColor: "#D21034",
  },
  {
    id: "curacao",
    name: "Curaçao",
    flag: "/flags/curacao.svg",
    region: "North America",
    group: "E",
    fifaRanking: 81,
    coach: "Dick Advocaat",
    keyPlayers: ["Leandro Bacuna", "Jürgen Locadia", "Cuco Martina"],
    worldCupHistory: "First appearance",
    qualification: "CONCACAF",
    teamId: "1895293",
    appearances: 0,
    hostTeam: false,
    primaryColor: "#236CDA",
    secondaryColor: "#FFCE1F",
  },
  {
    id: "new-zealand",
    name: "New Zealand",
    flag: "/flags/new-zealand.svg",
    region: "Oceania",
    group: "G",
    fifaRanking: 85,
    coach: "Darren Bazeley",
    keyPlayers: ["Chris Wood", "Sarpreet Singh", "Michael Boxall"],
    worldCupHistory: "Best: Group Stage (2010)",
    qualification: "OFC",
    teamId: "43978",
    appearances: 2,
    hostTeam: false,
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "uzbekistan",
    name: "Uzbekistan",
    flag: "/flags/uzbekistan.svg",
    region: "Asia",
    group: "K",
    fifaRanking: 52,
    coach: "Srečko Katanec",
    keyPlayers: [
      "Eldor Shomurodov",
      "Otabek Shukurov",
      "Jaloliddin Masharipov",
    ],
    worldCupHistory: "First appearance",
    qualification: "AFC",
    teamId: "44005",
    appearances: 0,
    hostTeam: false,
    primaryColor: "#112BB3",
    secondaryColor: "#1EB53A",
  },
];

// Region filters
export const regions = [
  { id: "all", name: "All Regions" },
  { id: "europe", name: "Europe" },
  { id: "south-america", name: "South America" },
  { id: "north-america", name: "North America" },
  { id: "africa", name: "Africa" },
  { id: "asia", name: "Asia" },
  { id: "oceania", name: "Oceania" },
];
