export const upcomingMatches = [
  {
    id: 1,
    date: "2023-11-15",
    time: "21:00",
    league: "La Liga",
    leagueId: "laliga",
    homeTeam: { name: "Villarreal", logo: "/icons/villarreal.svg" },
    awayTeam: { name: "Espanyol", logo: "/icons/espanyol.svg" },
    stadium: "Estadio de la Cerámica",
  },
  {
    id: 2,
    date: "2023-11-15",
    time: "21:45",
    league: "Ligue 1",
    leagueId: "ligue1",
    homeTeam: { name: "Nantes", logo: "/icons/nantes.svg" },
    awayTeam: { name: "Toulouse", logo: "/icons/toulouse.svg" },
    stadium: "Stade de la Beaujoire",
  },
  {
    id: 3,
    date: "2023-11-16",
    time: "18:30",
    league: "Ligue 1",
    leagueId: "ligue1",
    homeTeam: { name: "Montpellier", logo: "/icons/montpellier.svg" },
    awayTeam: { name: "Reims", logo: "/icons/reims.svg" },
    stadium: "Stade de la Mosson",
  },
  {
    id: 4,
    date: "2023-11-16",
    time: "20:00",
    league: "Ligue 1",
    leagueId: "ligue1",
    homeTeam: { name: "Lens", logo: "/icons/lens.svg" },
    awayTeam: { name: "Auxerre", logo: "/icons/auxerre.svg" },
    stadium: "Stade Bollaert-Delelis",
  },
  {
    id: 5,
    date: "2023-11-17",
    time: "20:45",
    league: "Premier League",
    leagueId: "premier",
    homeTeam: { name: "Liverpool", logo: "/icons/liverpool.svg" },
    awayTeam: { name: "Tottenham", logo: "/icons/tottenham.svg" },
    stadium: "Anfield",
  },
  {
    id: 6,
    date: "2023-11-17",
    time: "20:30",
    league: "Bundesliga",
    leagueId: "bundesliga",
    homeTeam: { name: "Werder Bremen", logo: "/icons/bremen.svg" },
    awayTeam: { name: "FC St. Pauli", logo: "/icons/stpauli.svg" },
    stadium: "Weserstadion",
  },
];
