export const worldCupMatches = [
  {
    id: "1",
    title: "Brazil vs Argentina",
    description: "FIFA World Cup 2026 - Group A",
    isLive: true,
    tournament: "FIFA World Cup 2026",
    phase: "Group Stage",
    group: "Group A",
    stadium: "MetLife Stadium",
    city: "East Rutherford, NJ",
    country: "USA",
    viewers: "2.8M",
    homeTeam: {
      name: "Brazil",
      code: "BRA",
      flag: "/placeholder.svg?height=64&width=64&text=BR",
      score: 2,
      fifaRanking: 1,
      coach: "Dorival Júnior",
    },
    awayTeam: {
      name: "Argentina",
      code: "ARG",
      flag: "/placeholder.svg?height=64&width=64&text=AR",
      score: 1,
      fifaRanking: 2,
      coach: "Lionel Scaloni",
    },
    time: "LIVE",
    minute: 78,
    date: "2026-06-15",
    kickoff: "20:00",
    temperature: "75°F",
    attendance: "82,500",
    referee: "Björn Kuipers (Netherlands)",
    stats: {
      possession: [52, 48],
      shots: [15, 12],
      shotsOnTarget: [7, 5],
      corners: [6, 4],
      fouls: [8, 10],
      yellowCards: [2, 3],
      redCards: [0, 0],
      offsides: [3, 2],
      saves: [4, 5],
    },
    keyPlayers: {
      home: ["Vinícius Jr.", "Casemiro", "Alisson"],
      away: ["Lionel Messi", "Ángel Di María", "Emiliano Martínez"],
    },
  },
  {
    id: "2",
    title: "France vs Germany",
    description: "FIFA World Cup 2026 - Quarter Final",
    isLive: true,
    tournament: "FIFA World Cup 2026",
    phase: "Quarter Final",
    group: null,
    stadium: "SoFi Stadium",
    city: "Los Angeles, CA",
    country: "USA",
    viewers: "3.2M",
    homeTeam: {
      name: "France",
      code: "FRA",
      flag: "/placeholder.svg?height=64&width=64&text=FR",
      score: 1,
      fifaRanking: 3,
      coach: "Didier Deschamps",
    },
    awayTeam: {
      name: "Germany",
      code: "GER",
      flag: "/placeholder.svg?height=64&width=64&text=DE",
      score: 1,
      fifaRanking: 4,
      coach: "Julian Nagelsmann",
    },
    time: "LIVE",
    minute: 65,
    date: "2026-07-02",
    kickoff: "17:30",
    temperature: "82°F",
    attendance: "70,240",
    referee: "Antonio Mateu Lahoz (Spain)",
    stats: {
      possession: [48, 52],
      shots: [11, 14],
      shotsOnTarget: [4, 6],
      corners: [5, 7],
      fouls: [12, 8],
      yellowCards: [3, 2],
      redCards: [0, 0],
      offsides: [2, 4],
      saves: [5, 3],
    },
    keyPlayers: {
      home: ["Kylian Mbappé", "Antoine Griezmann", "Hugo Lloris"],
      away: ["Jamal Musiala", "Joshua Kimmich", "Manuel Neuer"],
    },
  },
  {
    id: "3",
    title: "Spain vs Netherlands",
    description: "FIFA World Cup 2026 - Group B",
    isLive: false,
    tournament: "FIFA World Cup 2026",
    phase: "Group Stage",
    group: "Group B",
    stadium: "Estadio Azteca",
    city: "Mexico City",
    country: "Mexico",
    viewers: "0",
    homeTeam: {
      name: "Spain",
      code: "ESP",
      flag: "/placeholder.svg?height=64&width=64&text=ES",
      score: 0,
      fifaRanking: 5,
      coach: "Luis de la Fuente",
    },
    awayTeam: {
      name: "Netherlands",
      code: "NED",
      flag: "/placeholder.svg?height=64&width=64&text=NL",
      score: 0,
      fifaRanking: 6,
      coach: "Ronald Koeman",
    },
    time: "Upcoming",
    minute: 0,
    date: "2026-06-18",
    kickoff: "20:45",
    temperature: "68°F",
    attendance: "87,523",
    referee: "Daniele Orsato (Italy)",
    stats: {
      possession: [0, 0],
      shots: [0, 0],
      shotsOnTarget: [0, 0],
      corners: [0, 0],
      fouls: [0, 0],
      yellowCards: [0, 0],
      redCards: [0, 0],
      offsides: [0, 0],
      saves: [0, 0],
    },
    keyPlayers: {
      home: ["Pedri", "Gavi", "Unai Simón"],
      away: ["Virgil van Dijk", "Frenkie de Jong", "Memphis Depay"],
    },
  },
];
